# Setup
title:        Track by Me
tagline:      TV Show & Movie Tracker for you!
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Onur & Gokcan & Fatih
  url:        http://trackby.github.io/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
