# Setup
title:        trackby.me
tagline:      TV Show & Movie Tracker for you!
baseurl:      ""
paginate:     1
future: true

# About/contact
author1:
  name:       Onur
  url:        http://github.com/sonmezonur

author2:
  name:    Gokcan
  url:     http://github.com/gokcan

author3:
  name:    Fatih
  url:   http://github.com/neonray

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
